%%%  This file is part of the Karlsruhe Seismology Processing (KaSP) Toolbox for MATLAB!

function [yr,mon,day,hr,mn,sec]=time2num(Tn,res)

% default resolution 1/100 sec =res
% this function has been created to turn around the problem of the function
% datevec in matlab:
%     datevec(datenum(2005,12,31,23,50,00)) -> 
%                                       [2005 12 31 23 49 59.9999923706055]


if nargin==1
    res=1/100;
end
k=24*60*60/res;

Tn=round(Tn*k)/k;

% optimisation for speed!
%new:
[yr mon day a b c]=datevec(fix(Tn));
% 
% old:
%yr=str2num(datestr(fix(Tn),'yyyy'));
%mon=str2num(datestr(fix(Tn),'mm'));
%day=str2num(datestr(fix(Tn),'dd'));

Th=round((Tn-fix(Tn))*k)/k; %because of the error generated by soustraction
                            %it's necessary to round again to remove it
                            %this error is close to k*eps
                            %to see that display: k*eps,Tn,Tn-fix(Tn),Th
hr=fix(Th*24);
mn=fix(round((Th*24-hr)*60*60/res)/60*res);
sec=round((Th*24*60-hr*60-mn)*60/res)*res;

if nargout<=1
    yr=[yr,mon,day,hr,mn,sec];
end

return
